columns=3

[[module]]
id=0
name="Getting Started"
url="getting-started"
icon="flag-fill"
column=0
next=[7]

[[module]]
id=7
name="Installing Software"
url="installing-software"
icon="cloud-download-fill"
column=0
next=[1]

[[module]]
id=1
name="Version Control"
url="version-control"
icon="file-diff-fill"
column=1
next=[2, 4]

[[module]]
id=2
name="Git"
url="git"
icon="git"
column=1
next=[3]

[[module]]
id=3
name="GitHub"
url="github"
icon="github"
column=1

[[module]]
id=4
name="Tools"
url="tools"
icon="hammer"
column=2
next=[5, 6]

[[module]]
id=5
name="Editors"
url="editors"
icon="text-left"
column=2

[[module]]
id=6
name="Licensing"
url="licensing"
icon="person-fill-lock"
column=3
